### ISSUE TITLE
Allow for custom Pelias URL, search/autocomplete endpoints, and sources

### ISSUE THREAD

**Issue by landonreed** [conveyal/isomorphic-mapzen-search#39]
@trevorgerhardt, TriMet is hosting their own instance of Pelias, so we'd like to make this library accept an optional parameters for:

- [x]  base Pelias/Mapzen URL (`mapzenUrl`),
- [x]  overrides for the search (`searchUrl`) and autocomplete (`autocompleteUrl`) endpoints, and
- [x] custom sources (e.g., the addition of the new `transit` source.

This issue is based on @fpurcell's suggestions here: https://github.com/conveyal/trimet-mod-otp/issues/2.

Do you see any issues here?  I'll work on a PR.

**Comment by landonreed** [comment]
Actually, it appears that `sources` is already a parameter with defaults that can be overridden.

**Comment by evansiroky** [comment]
Fixed w/ #40
